### ISSUE TITLE
💡 [REQUEST] - <Customer idx & columns EDA >

### ISSUE THREAD

**Issue by LeeJuHwan** [LgDNet/phase2_module#8]
### Idea Request

- Customer idx와 customer_job의 값을 합쳐. 같은 기업이지만, 누가 신청하냐에 따른 결과 확인 필요.
- Customer idx와 lead_owener의 값을 합쳐, 같은 기업이지만, 누가 담당했는지에 따른 결과 확인 필요.
- Customer idx와 business_area의 값을 합쳐, 같은 기업이지만, 같은 사업 영역을 담당하는지 결과 확인 필요.
- Customer_Job에 따른 영업 전환 비율도 확인.

**Comment by Sbeom12** [comment]
추가적으로 고객의 지위가 높을수록 더 전환율이 높을것이다.

**Comment by Sbeom12** [comment]
seniority_level,job_function 전처리 필요.

**Comment by Sbeom12** [comment]
business_area null값 채우기 방법

* customer_idx, 참고
